version: '3.4'
services:
  web:
    image: kaspermartensen/bakeweb
    ports:
      - "5000:80"
    environment:
      - API_URL=http://api:80
  api:
    image: kaspermartensen/bakeapi
    ports:
      - "6000:80"
